"""initial schema

Revision ID: 2f92ffe854a3
Revises: 
Create Date: 2026-01-19 22:09:32.013596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f92ffe854a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='chk_tenant_email'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_tenants_created', 'tenants', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_tenants_email', 'tenants', ['email'], unique=True)
    op.create_table('condominiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_condominiums_name', 'condominiums', ['name'], unique=False)
    op.create_index('idx_condominiums_tenant', 'condominiums', ['tenant_id'], unique=False)
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('visual_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'visual_number', name='uq_tenant_visual_number'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_qr_codes_active', 'qr_codes', ['tenant_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_qr_codes_tenant', 'qr_codes', ['tenant_id'], unique=False)
    op.create_index('idx_qr_codes_token', 'qr_codes', ['token'], unique=True)
    op.create_index('idx_qr_codes_visual', 'qr_codes', ['tenant_id', 'visual_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('property_manager', 'assembly_operator', name='user_role'), server_default='assembly_operator', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='chk_user_email'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_deleted', 'users', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_tenant', 'users', ['tenant_id'], unique=False)
    op.create_table('assemblies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('assembly_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('assembly_type', sa.Enum('ordinary', 'extraordinary', name='assembly_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'finished', name='assembly_status'), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('assembly_date >= created_at', name='chk_assembly_date'),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominiums.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assemblies_condo_date', 'assemblies', ['condominium_id', sa.literal_column('assembly_date DESC')], unique=False)
    op.create_index('idx_assemblies_condominium', 'assemblies', ['condominium_id'], unique=False)
    op.create_index('idx_assemblies_date', 'assemblies', [sa.literal_column('assembly_date DESC')], unique=False)
    op.create_index('idx_assemblies_operator', 'assemblies', ['operator_id'], unique=False)
    op.create_index('idx_assemblies_status', 'assemblies', ['status'], unique=False)
    op.create_table('agendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('pending', 'open', 'closed', 'cancelled', name='agenda_status'), server_default='pending', nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("(status = 'open' AND opened_at IS NOT NULL) OR (status != 'open' AND (closed_at IS NULL OR closed_at >= opened_at))", name='chk_agenda_dates'),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assembly_id', 'display_order', name='chk_agenda_order')
    )
    op.create_index('idx_agendas_assembly', 'agendas', ['assembly_id'], unique=False)
    op.create_index('idx_agendas_order', 'agendas', ['assembly_id', 'display_order'], unique=False)
    op.create_index('idx_agendas_status', 'agendas', ['status'], unique=False)
    op.create_table('assembly_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(length=50), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('ideal_fraction', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('ideal_fraction > 0 AND ideal_fraction <= 100', name='chk_unit_ideal_fraction'),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assembly_id', 'unit_number', name='uq_assembly_unit_number')
    )
    op.create_index('idx_assembly_units_assembly', 'assembly_units', ['assembly_id'], unique=False)
    op.create_index('idx_assembly_units_owner', 'assembly_units', ['owner_name'], unique=False)
    op.create_table('qr_code_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('qr_code_id', sa.Integer(), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assembly_id', 'qr_code_id', name='uq_qr_per_assembly')
    )
    op.create_index('idx_qr_assignments_assembly', 'qr_code_assignments', ['assembly_id'], unique=False)
    op.create_index('idx_qr_assignments_assigned_by', 'qr_code_assignments', ['assigned_by'], unique=False)
    op.create_index('idx_qr_assignments_qr', 'qr_code_assignments', ['qr_code_id'], unique=False)
    op.create_table('agenda_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agenda_id', 'display_order', name='uq_agenda_option_order')
    )
    op.create_index('idx_agenda_options_agenda', 'agenda_options', ['agenda_id'], unique=False)
    op.create_index('idx_agenda_options_order', 'agenda_options', ['agenda_id', 'display_order'], unique=False)
    op.create_table('qr_code_assigned_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('assembly_unit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assembly_unit_id'], ['assembly_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignment_id'], ['qr_code_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'assembly_unit_id', name='uq_assignment_unit')
    )
    op.create_index('idx_qr_assigned_units_assignment', 'qr_code_assigned_units', ['assignment_id'], unique=False)
    op.create_index('idx_qr_assigned_units_unit', 'qr_code_assigned_units', ['assembly_unit_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('assembly_unit_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('(is_valid = TRUE AND invalidated_at IS NULL AND invalidated_by IS NULL) OR (is_valid = FALSE AND invalidated_at IS NOT NULL AND invalidated_by IS NOT NULL)', name='chk_invalidation'),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assembly_unit_id'], ['assembly_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invalidated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['option_id'], ['agenda_options.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agenda_id', 'assembly_unit_id', name='uq_vote_per_unit_agenda')
    )
    op.create_index('idx_votes_agenda', 'votes', ['agenda_id'], unique=False)
    op.create_index('idx_votes_option', 'votes', ['option_id'], unique=False)
    op.create_index('idx_votes_unit', 'votes', ['assembly_unit_id'], unique=False)
    op.create_index('idx_votes_valid', 'votes', ['agenda_id', 'is_valid'], unique=False, postgresql_where=sa.text('is_valid = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_votes_valid', table_name='votes', postgresql_where=sa.text('is_valid = TRUE'))
    op.drop_index('idx_votes_unit', table_name='votes')
    op.drop_index('idx_votes_option', table_name='votes')
    op.drop_index('idx_votes_agenda', table_name='votes')
    op.drop_table('votes')
    op.drop_index('idx_qr_assigned_units_unit', table_name='qr_code_assigned_units')
    op.drop_index('idx_qr_assigned_units_assignment', table_name='qr_code_assigned_units')
    op.drop_table('qr_code_assigned_units')
    op.drop_index('idx_agenda_options_order', table_name='agenda_options')
    op.drop_index('idx_agenda_options_agenda', table_name='agenda_options')
    op.drop_table('agenda_options')
    op.drop_index('idx_qr_assignments_qr', table_name='qr_code_assignments')
    op.drop_index('idx_qr_assignments_assigned_by', table_name='qr_code_assignments')
    op.drop_index('idx_qr_assignments_assembly', table_name='qr_code_assignments')
    op.drop_table('qr_code_assignments')
    op.drop_index('idx_assembly_units_owner', table_name='assembly_units')
    op.drop_index('idx_assembly_units_assembly', table_name='assembly_units')
    op.drop_table('assembly_units')
    op.drop_index('idx_agendas_status', table_name='agendas')
    op.drop_index('idx_agendas_order', table_name='agendas')
    op.drop_index('idx_agendas_assembly', table_name='agendas')
    op.drop_table('agendas')
    op.drop_index('idx_assemblies_status', table_name='assemblies')
    op.drop_index('idx_assemblies_operator', table_name='assemblies')
    op.drop_index('idx_assemblies_date', table_name='assemblies')
    op.drop_index('idx_assemblies_condominium', table_name='assemblies')
    op.drop_index('idx_assemblies_condo_date', table_name='assemblies')
    op.drop_table('assemblies')
    op.drop_index('idx_users_tenant', table_name='users')
    op.drop_index('idx_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_deleted', table_name='users', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('users')
    op.drop_index('idx_qr_codes_visual', table_name='qr_codes')
    op.drop_index('idx_qr_codes_token', table_name='qr_codes')
    op.drop_index('idx_qr_codes_tenant', table_name='qr_codes')
    op.drop_index('idx_qr_codes_active', table_name='qr_codes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('qr_codes')
    op.drop_index('idx_condominiums_tenant', table_name='condominiums')
    op.drop_index('idx_condominiums_name', table_name='condominiums')
    op.drop_table('condominiums')
    op.drop_index('idx_tenants_email', table_name='tenants')
    op.drop_index('idx_tenants_created', table_name='tenants')
    op.drop_table('tenants')
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
    # ### end Alembic commands ###
